language: generic
services:
- docker
env:
  global:
  - secure: XrlHu62smyr8wXivBX7/ddVQkA2YGjQcx5iDUaOO3iOa9ZCDE7/lE+a7TclOZhFyPczdR0SnpP0Uz7EnEdFxFSAORVS+yhRdTzTba/oPiD0jRQQroNNZEBmpOrpfAHMHcC1nTwD6pfjPkl6FSHIRt3npJjXbJZB1z7DuASOJm0tmPkttpYvmuxZ9qh1Lh/0aRUPQDAfp1LH4lFXRni093FK6HIF9AGly+vSp7vewpwbDxwQZTkwP4C/ZDKRFvwqSQsrvvxgG4SzRux7Wp5qjDRWZXoedl/vbDuS6orx/FD0M9r8HiZCRO1c2xs+mU5a8UhzguUdGAzYctlF55ufoQNkoMPhQ81x6FHEYs2F1PHkKF1X2Ht/phTNJc4wp5difZYZbx/x9vpnC0mLSev3a6g1ztGK9+LGjzIiSSVX9WQt1/SOuQZTvITJW3ik0CXR1Zws7WfjINP35pb/VwMgCREEZMhDhuSsBu2Ehv4DcmyLqVWwx/7a2wqfblmuWSDRWx/8mLG+Je7aSvzoZMn45iIWWjnPWHl8wgsS//fwsdyCRyyQJqXm2RpwZPZigyZR01vAQOBv5G0JprArMbEF5OLzAxn5q2/oL1tKRZll97aBbDdEc+snAgoxYzevl7/sCmfScEeHky/H1PXE+FfS0zHg0pqhsc1yK/M8j5kcj9h0=
  - secure: C0oAAmB58L/ytA9SX7s7MFtnF3iDFkI8gemkCr3T11Y1euGeXzWaePivHGJfIYA1gHxz66csVc5bSYRechYlh/JrVn8MzkvyieQMAPzye8Sv4aPolOBA/tUa4HsynnLXkXxMJzCDkgEqP7NXBPZKtIrzzmRoLftFqv5zyh5pAUix/ljIGc4uzjuBKMrv8QaSMtrn6OF5UV6ZKLaaExMHOvhrnKlCnQq4Fe/3PF/XmXZwYyRksPRKoetvKNMHAogGSSupQ/OYOwvLAE76iqGQ6b6lwOobCdOvJdhnGXBK+7Vvs3EyS5o1Z0JTJeuRzbaaS4iYarRREcJ9x6KW9yFE2j2CdrYTSEYTvsy9PTbiQF5Jf14JsugcoGQ5D1cB6JGvYr6RVzSabIg3K0mtVGz9Q2pU+XtAbUWxLaaq5pf/MjaahlQRKo6akQvt6K1/1HGdvVKGOcEFM5Bha1zPKVTP50gfyBf+LdhdTIGq3gFdKxe3KmL6hxvAin7Inxx5Pg+n7GTp76c0pASeUVYNV0IlS5mlrfcaqmmSiFPs7h5hlNRiCW4hm2JAcHG1s1NjBmqeWxT/rrBDI/0hjijklm57md29srJg88c83NLNYEO4Cpb7F+BwOIq8F8byttbg2bmK0b36yIxgxV3VzOMa6g/pqoPRV6oooA8cxPyd80TTVw0=
install:
- make ci-build
- make ci-run
script:
- make ci-test
after_success:
- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then make ci-push-tag TAG="${TRAVIS_PULL_REQUEST_BRANCH////_}";
  fi
deploy:
- provider: script
  script: make ci-push
  on:
    branch: master
