language: generic

services:
- docker

env:
  global:
  # DOCKER_USERNAME
  - secure: DSbqaAWpFZPpNG15P3gdEmKo6YmEb/MAnGakXnn8FkoExhxORJD7a5VjNpcxIWXdMahORkA5b60k7x8hGpRc59DbANLarf1WmLOTY+WnZFPmpj4WHE1ufbHdfY93a/Y8X8vPUxYewuz9kKBStG3mCDYnsBpwo8WwYUz6wvALXqsVOYlgGqz548r+DzhfmBZhUrX669exS02Yk9lxge9ZQr/PrgrRgRh1whtpioEGmSRka/AtsB+ABnX8kzoGKQF5ZOo+N2ZljRb5suLO98vV3Gpp9FplIeo1hG8GarGvjLHAXMN9WWo3frG4p8igKG+ap5rkdL+xP4OaktpB9xgThQNaMsNXKo7y3wXS6Gj5nJSyaYeSSgYAEZVYjRBo0HDJ7jBk5MdxdPEqMF56F+Yfc6D/ONYZdvEGoteIWV1EFirnkyla3YbhR6Yt8vUXLO9dIZomPaiDQ+/E/iPwhIpTXeEziLnU0jvD22IBu+HCcYXVqVXMNBn1zMO85svtUfEaTqOMOab2fDDa9F3YNaxVDQzEO7/iQch75uY0grEHgwOkZYv8+eVCn3pENOhpR1cBjDodQJA16XVLNilYb9Ls3DXct4Ez5lOnTSMZcI5JVFO8Mri8r3cwK2U2KBxnlAmIOJbouZtxPNwhEKma4HC7Aw1Z95QoasDy6DUZenKUAoc=
  # DOCKER_PASSWORD
  - secure: OwG0M4waPV+5HKleLBiB0bZOipQHU7N3UFnwdYBWs37HDUUwrNjjLOfBnMHbsumOsa4ECRsShT36rAHdDdbhfypJYR0eiKtEmOwfi7qHcD6jlfFahFM7qtr69n6jQPoISpwWIYk5/VBB1r82kyh/deJbN6j+dQ0kV4fB5Q/9qbWR0K2o0IfvQD/aj5FzA1pvLeaeCp0CUJKKKe7IEwULnzMLRsX9C4SiYCRdvnrQ+FQYMD3Dh7oFh+0BQ81Zlmo9GhYCkEDDcx7FXe47BMRdZ1ipAGwoLGEcWTKnbsdeh5RHVMniwV+vIqag+yxU3pa6QxlQrfvvCJN5OuT684FxkyWt7SOvShXBGL4bjusC6HCVXlt1sLHVnES6LabF1ODXfma/QZU9Ul4vCRjl7VszOYRtS+oalgcBfnEzhUlN1Tr2nxCc96qFlVyshCRcrJ2ovlcD7EX1kToVjuaj6vudPsHUv6X0GSOGQXsdv4lasRasOCwZEtP/vFAyHHFyVBUYn8njkzNXB1M3s7FNmZ/Vv8uVdnJbe4dv5yLG/lcPp3HieMadQeJPxO988kY93keHX2bk8j/Z4L+/o0dQ5DtEnmD0C2HnpDgEmZe2oK0cHAGfWLm6iN8shgz4B9Xdjl7fB5odbLBrqQzuQDW+NYO8R47bV8r4+eZbAPY/R865ECk=

before_install:
- openssl aes-256-cbc -K $encrypted_d130a8d51d28_key -iv $encrypted_d130a8d51d28_iv -in .htpasswd.enc -out .htpasswd -d

install:
- make ci-build
- make ci-run

script:
- make ci-test

after_success:
- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then make ci-push-tag TAG="${TRAVIS_PULL_REQUEST_BRANCH////_}";
  fi

deploy:
- provider: script
  script: make ci-push
  on:
    branch: master
